name: Terraform Destroy (Org Accounts)

on:
  workflow_dispatch:   # déclenché à la main

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-1

    concurrency:
      group: terraform-org-accounts
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC (Management Account)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ORG_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -input=false -out=tfdestroy

      - name: Terraform Destroy
        run: terraform apply -input=false -auto-approve tfdestroy
